language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - make all
  - coverage run -m unittest discover --start-directory tests --verbose
after_success:
  - coveralls